'use client';

import { useEffect, useState, Suspense } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import type { Incident } from '@/types';
import { supabase, MOCK_MODE } from '@/lib/supabase';
import { MOCK_INCIDENTS } from '@/lib/mock-data';
import IncidentMap from '@/components/IncidentMap';
import { playAlertSound } from '@/lib/alertSound';
import { useIsMobile } from '@/lib/useIsMobile';
import { usePassengerNames } from '@/lib/usePassengerNames';
import { CloseIcon, ShieldIcon } from '@/components/icons/Icons';
import AppTopBar from '@/components/AppTopBar';
import AddPassengerModal from '@/components/AddPassengerModal';

const C = { ink: '#090909', panel: 'rgba(17,17,17,.96)', line: '#2a2a2a', paper: '#f3f1ec', muted: '#97958f', red: '#df5149', redBg: '#2b1716', green: '#b8d192', greenBg: '#1a2419', stone: '#252421' };
const dots = 'radial-gradient(circle, rgba(255,255,255,.08) 1px, transparent 1.2px)';

function timeAgo(value: string) { const min = Math.floor((Date.now() - new Date(value).getTime()) / 60000); return min < 1 ? 'just now' : min < 60 ? `${min}m ago` : min < 1440 ? `${Math.floor(min / 60)}h ago` : `${Math.floor(min / 1440)}d ago`; }
const panel = { background: C.panel, border: `1px solid ${C.line}`, borderRadius: 6, boxShadow: '0 18px 48px rgba(0,0,0,.34)', backgroundImage: dots, backgroundSize: '22px 22px' } as const;

function DashboardPageInner() {
  const router = useRouter(); const isMobile = useIsMobile(); const passengerName = usePassengerNames(); const filterPassenger = useSearchParams().get('passenger');
  const [incidents, setIncidents] = useState<Incident[]>([]); const [loading, setLoading] = useState(true); const [selectedId, setSelectedId] = useState<string | null>(null); const [feedOpen, setFeedOpen] = useState(false); const [addOpen, setAddOpen] = useState(false); const [clock, setClock] = useState('');
  useEffect(() => { const update = () => setClock(new Date().toLocaleTimeString()); update(); const id = setInterval(update, 1000); return () => clearInterval(id); }, []);
  useEffect(() => { async function load() { if (MOCK_MODE) { setIncidents(MOCK_INCIDENTS); setLoading(false); return; } const { data } = await supabase!.from('incidents').select('*').order('created_at', { ascending: false }).limit(50); if (data) setIncidents(data as Incident[]); setLoading(false); } load(); }, []);
  useEffect(() => { if (MOCK_MODE || !supabase) return; const client = supabase; const channel = client.channel('incidents-realtime').on('postgres_changes', { event: 'INSERT', schema: 'public', table: 'incidents' }, ({ new: item }: { new: Incident }) => { setIncidents(old => [item, ...old]); playAlertSound(); }).on('postgres_changes', { event: 'UPDATE', schema: 'public', table: 'incidents' }, ({ new: item }: { new: Incident }) => setIncidents(old => old.map(i => i.id === item.id ? item : i))).subscribe(); return () => { client.removeChannel(channel); }; }, []);
  const displayed = filterPassenger ? incidents.filter(i => i.passenger_id === filterPassenger) : incidents; const active = displayed.filter(i => i.status === 'active'); const resolved = displayed.filter(i => i.status === 'resolved'); const selected = displayed.find(i => i.id === selectedId); const today = displayed.filter(i => new Date(i.created_at).toDateString() === new Date().toDateString()).length; const rate = displayed.length ? Math.round(resolved.length / displayed.length * 100) : 0;
  const select = (id: string) => { setSelectedId(id); if (isMobile) setFeedOpen(false); };
  const simulate = () => { const spread = () => (Math.random() - .5) * .08; setIncidents(old => [{ id: `sim-${Date.now()}`, passenger_id: 'demo-passenger-001', latitude: 6.5244 + spread(), longitude: 3.3792 + spread(), trigger_type: Math.random() > .5 ? 'audio' : 'manual', audio_url: null, status: 'active', created_at: new Date().toISOString() }, ...old]); playAlertSound(); };
  const pill = (text: string, color: string, bg: string) => <span style={{ display: 'inline-flex', alignItems: 'center', gap: 7, color, background: bg, border: `1px solid ${color}33`, borderRadius: 4, padding: '7px 10px', fontSize: 11, fontWeight: 800, letterSpacing: '.04em' }}>{text}</span>;
  return <div style={{ minHeight: '100vh', background: C.ink, color: C.paper, fontFamily: 'Inter, ui-sans-serif, system-ui, sans-serif' }}>
    <IncidentMap incidents={displayed} onMarkerClick={select} />
    <AppTopBar variant="floating" extraDesktopControls={<><span>{pill(`${active.length} ACTIVE`, active.length ? C.red : C.green, active.length ? C.redBg : C.greenBg)}</span><button onClick={() => setAddOpen(true)} style={{ border: `1px solid ${C.line}`, background: C.stone, color: C.paper, borderRadius: 4, padding: '7px 10px', fontSize: 11, fontWeight: 800, cursor: 'pointer' }}>+ Add traveller</button><button onClick={simulate} style={{ border: `1px solid #6d302d`, background: C.redBg, color: '#f7867e', borderRadius: 4, padding: '7px 10px', fontSize: 11, fontWeight: 800, cursor: 'pointer' }}>Simulate</button></>} extraMobileControls={[{ label: '+ Add traveller', color: C.paper, onClick: () => setAddOpen(true) }, { label: 'Simulate incident', color: C.red, onClick: simulate }]} />
    {!isMobile ? <aside style={{ ...panel, position: 'absolute', top: 76, left: 16, bottom: 16, width: 326, zIndex: 10, display: 'flex', flexDirection: 'column', overflow: 'hidden' }}><FeedHeader /><FeedList loading={loading} incidents={displayed} selectedId={selectedId} onSelect={select} passengerName={passengerName} /></aside> : <>{!feedOpen && <button onClick={() => { setFeedOpen(true); setSelectedId(null); }} style={{ ...panel, position: 'fixed', bottom: 16, left: 16, zIndex: 15, padding: '10px 13px', color: C.paper, fontWeight: 800, fontSize: 12 }}><i style={{ display: 'inline-block', width: 7, height: 7, borderRadius: '50%', background: active.length ? C.red : C.green, marginRight: 7 }} />INCIDENT FEED · {displayed.length}</button>}{feedOpen && <aside style={{ ...panel, position: 'fixed', inset: 'auto 0 0', maxHeight: '70vh', zIndex: 25, display: 'flex', flexDirection: 'column', borderRadius: '14px 14px 0 0', overflow: 'hidden' }}><FeedHeader onClose={() => setFeedOpen(false)} /><FeedList loading={loading} incidents={displayed} selectedId={selectedId} onSelect={select} passengerName={passengerName} /></aside>}</>}
    {selected && <IncidentDetail incident={selected} name={passengerName(selected.passenger_id)} mobile={isMobile} onClose={() => setSelectedId(null)} onRespond={() => router.push(`/dashboard/incidents/${selected.id}`)} />}
    {!(isMobile && (feedOpen || selected)) && <div style={{ ...panel, position: 'absolute', left: '50%', bottom: isMobile ? 72 : 16, transform: 'translateX(-50%)', zIndex: 10, display: 'flex', overflow: 'hidden' }}>{[['Today', today], ['Resolved', `${rate}%`], ['Total', displayed.length]].map(([label, value], index) => <div key={String(label)} style={{ padding: isMobile ? '8px 13px' : '10px 19px', minWidth: 75, textAlign: 'center', borderLeft: index ? `1px solid ${C.line}` : 'none' }}><b style={{ display: 'block', color: C.paper, fontSize: isMobile ? 14 : 18 }}>{value}</b><span style={{ color: C.muted, fontSize: 10, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '.08em' }}>{label}</span></div>)}</div>}
    {!isMobile && <div style={{ ...panel, position: 'absolute', right: 16, bottom: 16, zIndex: 10, padding: '8px 11px', color: C.muted, fontFamily: 'ui-monospace, monospace', fontSize: 11 }}>{MOCK_MODE ? 'DEMO' : 'LIVE'} · {clock || '--:--:--'}</div>}
    <AddPassengerModal isOpen={addOpen} onClose={() => setAddOpen(false)} onSuccess={() => router.refresh()} />
  </div>;
}

function FeedHeader({ onClose }: { onClose?: () => void }) { return <header style={{ padding: '16px 17px', borderBottom: `1px solid ${C.line}`, display: 'flex', justifyContent: 'space-between', alignItems: 'center', background: '#151515' }}><div><span style={{ display: 'block', color: C.paper, fontSize: 14, fontWeight: 800 }}>Incident feed</span><small style={{ color: C.muted, fontSize: 10, letterSpacing: '.08em', textTransform: 'uppercase' }}>Live monitoring</small></div>{onClose ? <button onClick={onClose} style={{ background: 'transparent', color: C.muted, border: 0 }}><CloseIcon size={16} /></button> : <span style={{ color: C.green, fontSize: 10, fontWeight: 800, letterSpacing: '.1em' }}>● LIVE</span>}</header>; }

function FeedList({ loading, incidents, selectedId, onSelect, passengerName }: { loading: boolean; incidents: Incident[]; selectedId: string | null; onSelect: (id: string) => void; passengerName: (id: string) => string }) { if (loading) return <p style={{ color: C.muted, textAlign: 'center', padding: 28, fontSize: 13 }}>Loading incidents…</p>; if (!incidents.length) return <div style={{ padding: '52px 20px', textAlign: 'center' }}><ShieldIcon size={28} color={C.green} /><p style={{ color: C.paper, fontWeight: 750, margin: '12px 0 4px' }}>All clear</p><p style={{ color: C.muted, fontSize: 12, margin: 0 }}>No incidents right now</p></div>; return <div style={{ flex: 1, overflowY: 'auto', padding: 8 }}>{incidents.map(inc => { const hot = inc.status === 'active'; const selected = inc.id === selectedId; return <button key={inc.id} onClick={() => onSelect(inc.id)} style={{ width: '100%', textAlign: 'left', padding: '13px 12px', marginBottom: 5, background: selected ? '#292421' : hot ? '#1c1211' : 'transparent', color: C.paper, border: selected ? '1px solid #51433f' : '1px solid transparent', borderLeft: `3px solid ${hot ? C.red : '#3d4b39'}`, borderRadius: 4, cursor: 'pointer' }}><div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 6 }}><span style={{ color: hot ? '#f17a72' : C.green, fontSize: 10, fontWeight: 800, letterSpacing: '.09em' }}>{hot ? '● ACTIVE ALERT' : 'RESOLVED'}</span><span style={{ color: C.muted, fontSize: 10 }}>{timeAgo(inc.created_at)}</span></div><b style={{ fontSize: 13, display: 'block', marginBottom: 4 }}>{passengerName(inc.passenger_id)}</b><span style={{ color: C.muted, fontSize: 11, fontFamily: 'ui-monospace, monospace' }}>{inc.latitude.toFixed(4)}, {inc.longitude.toFixed(4)}</span><div style={{ marginTop: 8 }}><span style={{ color: '#c4c0b7', background: '#282725', borderRadius: 3, padding: '3px 6px', fontSize: 10, fontWeight: 700 }}>{inc.trigger_type === 'audio' ? 'SOUND' : 'MANUAL TAP'}</span>{inc.audio_url && <span style={{ color: '#d7c398', marginLeft: 6, fontSize: 10, fontWeight: 700 }}>AUDIO</span>}</div></button>; })}</div>; }

function IncidentDetail({ incident, name, mobile, onClose, onRespond }: { incident: Incident; name: string; mobile: boolean; onClose: () => void; onRespond: () => void }) { const active = incident.status === 'active'; return <aside style={{ ...panel, position: mobile ? 'fixed' : 'absolute', top: mobile ? 'auto' : 76, right: mobile ? 0 : 16, bottom: mobile ? 0 : 'auto', left: mobile ? 0 : 'auto', width: mobile ? 'auto' : 340, maxHeight: mobile ? '75vh' : 'none', overflowY: 'auto', zIndex: 30, borderRadius: mobile ? '14px 14px 0 0' : 6 }}><header style={{ padding: '15px 17px', borderBottom: `1px solid ${C.line}`, display: 'flex', justifyContent: 'space-between' }}><span style={{ fontWeight: 800, fontSize: 14 }}>Incident detail</span><button onClick={onClose} style={{ background: 'transparent', color: C.muted, border: 0 }}><CloseIcon size={16} /></button></header><div style={{ padding: 18 }}><span style={{ display: 'inline-block', color: active ? '#f17a72' : C.green, background: active ? C.redBg : C.greenBg, padding: '5px 8px', borderRadius: 3, fontWeight: 800, fontSize: 10, letterSpacing: '.09em', marginBottom: 18 }}>{active ? '● ACTIVE ALERT' : 'RESOLVED'}</span>{[['Passenger', name], ['Latitude', incident.latitude.toFixed(6)], ['Longitude', incident.longitude.toFixed(6)], ['Trigger', incident.trigger_type === 'audio' ? 'Sound detected' : 'Manual tap'], ['Time', new Date(incident.created_at).toLocaleString()]].map(([title, value]) => <div key={title} style={{ marginBottom: 13 }}><small style={{ display: 'block', color: C.muted, fontSize: 10, textTransform: 'uppercase', letterSpacing: '.09em', marginBottom: 3 }}>{title}</small><span style={{ fontSize: 13, fontWeight: 650 }}>{value}</span></div>)}{incident.audio_url && !incident.audio_url.startsWith('mock://') && <audio controls src={incident.audio_url} style={{ width: '100%', margin: '5px 0 16px' }} />}<div style={{ display: 'flex', gap: 8, marginTop: 20 }}><a href={`https://www.google.com/maps?q=${incident.latitude},${incident.longitude}`} target="_blank" rel="noreferrer" style={{ flex: 1, textAlign: 'center', padding: '10px', color: C.paper, background: C.stone, border: `1px solid ${C.line}`, borderRadius: 4, fontSize: 12, fontWeight: 800, textDecoration: 'none' }}>Open map</a>{active && <button onClick={onRespond} style={{ flex: 1, padding: '10px', color: '#151515', background: C.paper, border: 0, borderRadius: 4, fontSize: 12, fontWeight: 800 }}>Respond</button>}</div></div></aside>; }

export default function DashboardPage() { return <Suspense fallback={<div style={{ minHeight: '100vh', display: 'grid', placeItems: 'center', background: C.ink, color: C.muted }}>Loading dashboard…</div>}><DashboardPageInner /></Suspense>; }
